Feat filter growers by number of captures
Greenstand/treetracker-query-api pull request #287
Opened 2023-03-03 20:00 UTC by OlhaD

2023-03-08 22:42 UTC, jeremydthomas requested changes
Over all this looks really good to me other than those 2 spots, honestly @dadiorchen I'd feel way more comfortable if someone better at SQL than me takes a quick glance at it as well. The SQL queries work in the database and everything though.

2023-03-09 03:18 UTC, dadiorchen commented on server/routers/growerAccountsRouter.ts
> +        captures_amount_max: Joi.number().integer().min(0),
min is correct to make sure a positive integer

2023-03-09 04:32 UTC, jeremydthomas commented on server/routers/growerAccountsRouter.ts
> +        captures_amount_max: Joi.number().integer().min(0),
Ah, that makes sense. I wasn't sure either way.

2023-03-11 17:41 UTC, OlhaD commented on server/routers/growerAccountsRouter.ts
> +        captures_amount_max: Joi.number().integer().min(0),
Same as in line 33, it should be .min to restrict negative values.

2023-03-11 22:26 UTC, jeremydthomas commented on server/routers/growerAccountsRouter.ts
> +        captures_amount_max: Joi.number().integer().min(0),
Sorry for the confusion @OlhaD , I was more so asking a question about it because I really didn't know for sure.

2023-03-26 20:11 UTC, merged