feat: add filter by geom for trees route
Greenstand/treetracker-query-api pull request #388
Opened 2024-12-27 04:42 UTC by dagmawig

fixes #387 

![image](https://github.com/user-attachments/assets/9fa9931c-b6a7-46e3-b065-b1c905609c29)

2024-12-27 04:47 UTC, dagmawig commented
@dadiorchen I have added tree search based on polygon filter functionality. Please review and let me know if you have feedback.

2025-01-07 10:27 UTC, dadiorchen requested changes

2025-01-07 10:27 UTC, dadiorchen commented on __tests__/e2e/trees.spec.ts
> +    'trees?lat=39.0619&lon=-122.6064&lat=38.1519&lon=-123.3139&lat=37.8879&lon=-121.1001',
@dagmawig we need you the standard data format for this, which is the geojson, so you need to give a parameter like `geojson` following the protocol: https://geojson.org/

2025-01-07 10:27 UTC, dadiorchen commented on __tests__/e2e/trees.spec.ts
> +    'trees?lat=39.0619&lon=-122.6064&lat=38.1519&lon=-123.3139&lat=37.8879&lon=-121.1001',
And also, postgresql recogonize geojson for example this: https://postgis.net/docs/ST_GeomFromGeoJSON.html

2025-01-22 02:38 UTC, dagmawig commented
@dadiorchen  I have made the changes to enable geojson array input as a parameter. It is still required to extract the latitude and longitude values to form lines of the polygon and perform a computation for trees inside the polygon in question. Let me know what you think.

2025-02-24 09:53 UTC, merged