Implement API: GET /wallets/{id} (get wallet info by name or id)
Greenstand/treetracker-query-api pull request #53
Opened 2022-01-21 00:49 UTC by pierrelstan

2022-01-21 01:31 UTC, dadiorchen commented
@pierrelstan did the e2e test pass?

2022-01-21 01:39 UTC, pierrelstan commented
> @pierrelstan did the e2e test pass?

@dadiorchen  locally it returns 
`{
"code": 500,
"message": "Unknown error (self signed certificate in certificate chain)"
}`

2022-01-25 19:24 UTC, pierrelstan commented
@dadiorchen  when I tried to query the wallet or wallets table :
`SELECT *  from wallet`  I got an error  ` SELECT *
          FROM wallet
           - relation "wallet" does not exist`
Does that mean I need to create a table's wallet before being able to get by id or name from the wallet?
or does the data for the wallet is from another table name?

2022-01-26 02:14 UTC, dadiorchen commented
use `wallet.wallet` instead, the former is the scheme name, we put wallet/token tables into the `wallet` schema in the postgresql

2022-01-27 00:43 UTC, pierrelstan commented
> use `wallet.wallet` instead, the former is the scheme name, we put wallet/token tables into the `wallet` schema in the PostgreSQL


Thank you.

2022-01-29 02:28 UTC, dadiorchen requested changes

2022-01-29 02:28 UTC, dadiorchen commented on README.md
> +DATABASE_URL=postgresql://doadmin:l5al4hwte8qmj6x8@db-postgresql-sfo2-nextgen-do-user-1067699-0.db.ondigitalocean.com:25060/treetracker?ssl=true NODE_TLS_REJECT_UNAUTHORIZED='0'  npm run test-e2e
@pierrelstan you need to hide the real database string, with some placeholder words/dummy string.

2022-01-29 02:28 UTC, dadiorchen commented on README.md
> +DATABASE_URL=postgresql://doadmin:l5al4hwte8qmj6x8@db-postgresql-sfo2-nextgen-do-user-1067699-0.db.ondigitalocean.com:25060/treetracker?ssl=true NODE_TLS_REJECT_UNAUTHORIZED='0'  npm run test-e2e
Otherwise the DB is easy to be hacked

2022-01-30 02:21 UTC, dadiorchen commented
@pierrelstan thank you, great job!

2022-01-30 02:21 UTC, merged