Get token by id
Greenstand/treetracker-query-api pull request #66
Opened 2022-02-01 13:08 UTC by pierrelstan

The following changes have been implemented for getting token by id:
- create e2e test & model test
- create Interface token 
- create TokensRepository 
- create tokens model
- create tokensRouter 
resolves #19

2022-02-05 00:15 UTC, pierrelstan commented
@dadiorchen, the e2e test passed successfully locally and npm run build too. 

But I noticed when I pushed my last changes to the branch,  the typescript compiles failed. 
Probably the issue comes from the configuration of typescript because where the error appears, the path is correct.

2022-02-05 01:57 UTC, dadiorchen commented
@QuaidBartolomei I experienced something too about the path, my case is that locally, the path is wrong, BUT, it works, but when I upload to github, it failed, because of the wrong relative path.

2022-02-11 03:39 UTC, QuaidBartolomei requested changes
You may need to run `npm install` to make sure your eslint and typescript packages are up to date.

2022-02-11 03:39 UTC, QuaidBartolomei commented on server/routers/tokensRouter.ts
> +import TokensModel from 'models/Tokens';
```suggestion
import TokensModel from 'models/tokens';
```

This caused a build error for me locally

2022-02-11 03:39 UTC, QuaidBartolomei commented on server/models/Tokens.spec.ts
> +import TokensModel from './Tokens';
```suggestion
import TokensModel from './tokens';
```

Eslint detected this error

2022-02-11 22:21 UTC, QuaidBartolomei requested changes
The filename of `models/token.ts` needs to be `models/Token.ts` to match the existing naming pattern in that directory. Can you revert those commits and change the filename instead?🙇  Sorry for being misleading before, I discovered the issue right away and did not initially think about the project structure. I should have edited those code comments once I realized.

2022-02-12 18:31 UTC, pierrelstan commented
> The filename of `models/token.ts` needs to be `models/Token.ts` to match the existing naming pattern in that directory. Can you revert those commits and change the filename instead?🙇 Sorry for being misleading before, I discovered the issue right away and did not initially think about the project structure. I should have edited those code comments once I realized.

Don't worry about it, I will make the changes.

2022-02-17 08:23 UTC, QuaidBartolomei requested changes
The test fails for me with this error:

```

  ● Tokens › /tokens/{tokenId}

    expect(received).toMatchObject(expected)

    - Expected  - 2
    + Received  + 2

      Object {
        "capture_id": "f6c0e710-d80a-4e93-a9d2-d4edb52856af",
        "claim": false,
    -   "created_at": "2021-02-18T23:53:29.172Z",
    +   "created_at": "2021-02-19T03:53:29.172Z",
        "id": "24f4f5f7-c29e-4707-961a-3515be5a2f3e",
        "transfer_pending": false,
        "transfer_pending_id": null,
    -   "updated_at": "2021-02-18T23:53:29.172Z",
    +   "updated_at": "2021-02-19T03:53:29.172Z",
        "wallet_id": "eecdf253-05b6-419a-8425-416a3e5fc9a0",
      }

       9 |
      10 |     expect(response.status).toBe(200);
    > 11 |     expect(response.body).toMatchObject({
         |                           ^
      12 |       id: '24f4f5f7-c29e-4707-961a-3515be5a2f3e',
      13 |       capture_id: 'f6c0e710-d80a-4e93-a9d2-d4edb52856af',
      14 |       wallet_id: 'eecdf253-05b6-419a-8425-416a3e5fc9a0',
```

It seems to be a timezone issue, I am 4 hours behind @pierrelstan and the test has a 4 hour difference. Removing those 2 lines passes the test.

2022-02-17 08:23 UTC, QuaidBartolomei commented on __tests__/e2e/tokens.spec.ts
> +      updated_at: '2021-02-18T23:53:29.172Z',
```suggestion
   //   created_at: '2021-02-18T23:53:29.172Z',
   //  updated_at: '2021-02-18T23:53:29.172Z',
```

We will comment it out as a reminder to resolve this issue

2022-02-21 23:17 UTC, QuaidBartolomei approved these changes

2022-02-22 01:35 UTC, dadiorchen commented
@pierrelstan thank you!

2022-02-22 01:35 UTC, merged